### ISSUE TITLE
not able to upload properly on moeboard software

### ISSUE THREAD

**Issue by pokeball99** [Seedmanc/Booru-mass-uploader#13]
`uploader.js:321 Refused to set unsafe header "Content-Length"SendFile.reader.onloadend @ uploader.js:321
uploader.js:9 POST http://reacted.example/post/create.json 413 (Request Entity Too Large)XMLHttpRequest.sendAsBinary @ uploader.js:9SendFile.reader.onloadend @ uploader.js:322
VM805:1 Uncaught SyntaxError: Unexpected token <SendFile.xhr.onreadystatechange @ uploader.js:284`
this appears to happen be it choosing folder or files, and also stops when a dupe is trying to upload to the server

**Comment by Seedmanc** [comment]
Great, now I'll never know which one of the recent updates caused the bug if at all.

> request entity too large

You sure you're not hitting the booru limit on file size here? Were you able to upload similar files before?

**Comment by pokeball99** [comment]
~~i mean, i am able to upload it ok sometimes, its when its hits a already uploaded file or gets the "too large" error when this happens~~ wait i just reread what you said, let me talk to the booru admin and ask him to see what the file limit is

**Comment by antonizoon** [comment]
To clarify, this is just a non-public instance of Moebooru, so the local ip address isn't all that useful.

I feel like I may have set an Nginx rule that limits the size of the content being sent, as is standard. Don't know if Moebooru has its own limits to be tweaked.

**Comment by Seedmanc** [comment]
> Uncaught SyntaxError: Unexpected token <

This probably means the server returns an error page instead of expected JSON message. I changed uploader.js a bit to support HTML responses. Try again and see what console tells you.

It's unexpected that it would fail on duplicates, but if you have a non-standard moebooru config that doesn't return JSON like the rest does, it might fail on any error.

**Comment by pokeball99** [comment]
hmm... ok, not sure what exactly happened, but after seeing that script had not been updated in at least 21 days (according to tampermonkey), i reinstalled it using the compiled one made 7 days ago on the repo(according to github commits), and now it is working

**Comment by pokeball99** [comment]
the following is a log of uploading ~100 images to the server
`helpers.min.js:6 
uploader.js:328 Refused to set unsafe header "Content-Length"SendFile.reader.onloadend @ uploader.js:328
http://redacted.example/post/create.json Failed to load resource: the server responded with a status of 423 (Locked)
uploader.js:328 Refused to set unsafe header "Content-Length"SendFile.reader.onloadend @ uploader.js:328
http://redacted.example/post/create.json Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
uploader.js:294 <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h6>413 Request Entity Too Large</h6></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

**Comment by Seedmanc** [comment]
Glad it got fixed (?), although the most work is done "server-side", since the uploader.js and helper.js are loaded from github, the .user.js doesn't change much and only affects the Mass Uploader link placement and initial engine detection.

You probably didn't have to include entire log seeing how it's all the same messages over. On another note I didn't know Github renders HTML in comments.
Να προσέχεις.
