### ISSUE TITLE
getting a blank page instead of the mass uploader

### ISSUE THREAD

**Issue by owengraven** [Seedmanc/Booru-mass-uploader#14]
Hi,

when loading up the mass uploader I get a blank page, don't know why, I removed and reinstalled the script in tampermonkey but still got the same issue.

catgirl.booru.org (NSFW) is my booru
and script version 1.3 with tampermonkey on chrome.

**Comment by Seedmanc** [comment]
Same as #10, it's caused by temporary unavailability of the CORS bypassing service at crossorigin.me.
Try accessing http://crossorigin.me/http://seedmanc.github.io/Booru-mass-uploader/index.html and see the 522 or a similar error.

Nothing I can do about it other than probably looking for an alternative service, suggestions are welcome.

**Comment by owengraven** [comment]
Oh ok, and i can't suggest anything, don't know much about those things.

**Comment by Seedmanc** [comment]
Actually, I've just added an alternative engine, so you should reinstall the user.js and it should work for now.

**Comment by Seedmanc** [comment]
I eliminated the CORS entirely, there should be no more issues like this.
Get the latest update https://github.com/Seedmanc/Booru-mass-uploader/raw/gh-pages/booru.mass.uploader.user.js
