### ISSUE TITLE
Drawfriends Booru-mass-uploader does not install on new Firefox 57 or upload with files on Chrome

### ISSUE THREAD

**Issue by ssmstzo** [Seedmanc/Booru-mass-uploader#20]
Hello,

I noticed after the update for Firefox 57 that the Booru-mass-uploader hasn't worked. When I try and install it through Firefox now it says the .js is corrupt. I know 57 just came out recently, but is there a workaround currently? Or am I doing something wrong. 

Also,

Chrome won't let me mass upload any photos, don't know if it's a booru problem or a problem with the uploader, just wanted to make you aware. Any input you have is greatly appreciated. Thanks.

**Comment by Seedmanc** [comment]
Works in both browsers for me. Could you please show the complete error message? How were you installing it? More info on Chrome would also help.

I'm not sure how you installed it as I couldn't find a way to do it with the new Greasemonkey other than manually modifying the link, try this https://rawgit.com/Seedmanc/Booru-mass-uploader/gh-pages/booru.mass.uploader.user.js

Also, if you were using a VPN or proxy to access your booru during uploading, that might be the issue, try one that supports SSL. It said "can't load index.html.js" when I tried a proxy without it.

**Comment by ssmstzo** [comment]
Thank you for the quick response. I tried the installer for firefox again and it worked...not sure if the link got modified but before it was just showing the code and not actually initiating the greasemonkey installer. It worked just now when I tried again. As for Chrome, I still get the attached error when I upload. It times out and then gives me that error when the firefox uploadeder worked no problem. Also I'm not using VPN or proxies to upload. Right now Chrome is my only issue. Appreciate any input you have on the Chrome version. Thanks!

Chrome error: https://i.imgur.com/a3IkdQJ.png

**Comment by Seedmanc** [comment]
Yeah I changed the links, github forces the filetype for direct links to txt instead of JS, apparently the old Greasemonkey didn't care but the new one failed to recognize it.

As for Chrome, one reason I can think of, are you accessing your booru via HTTPS (or perhaps you have an addon like HTTP everywhere)? Booru.org doesn't seem to have HTTPS access, but if you persist you might get to the upload page, which will still give a 404 when uploading.

I'll get to fixing that eventually, in the mean time try to use HTTP for your booru or switch to Firefox. By the way, seems like the folder upload mode works now with the new FF, so ignore the "chrome only" and try it as well.

**Comment by ssmstzo** [comment]
I'm not accessing it via HTTPS. I still tried the HTTP for access it and it still just sits and times out. Chrome is my preferred browser so if I can get it work on there all the better for me. Only Chrome add-ons I"m using are sad panda/4chan X/rikaikun/ABP and tumblr HQ. I don't think I've ever gotten the mass uploader to work on Chrome and was never sure why. In the mean time I can FF, but if you have any other input one why Chrome booru add-ons might not work for me it would be greatly appreciated. Thanks!

Is there any plan to allow Chrome to upload via files and not just by folder? 

Error: https://i.imgur.com/4qqAwae.png

**Comment by Seedmanc** [comment]
Well, I wonder what could be the problem then. I tried uploading to http://drawfriends.booru.org/ (this is the booru you mean, right?) myself via Chrome and it works.

Try disabling adblock on the uploader page, somebody reported having a problem with it back then, not sure it'd help here though.

Open browser console and see if there are  any particular errors there once upload fails (F12 - console).

As for folders, Chrome always supported files and folders upload, it's just FF didn't support folders back then so this feature was marked as Chrome-exclusive.

**Comment by ssmstzo** [comment]
Yep that's the one I'm trying to use. It's weird it still won't let me load even when I turn off adblock and when I checked the console no errors came up. Still works perfectly for me on FF. It's really weird and now that I think about it I think the uploader on drawfriends mostly never worked for me. In the mean time using FF is fine and I'll play around somemore with Chrome to see if anything works. Either way I can upload drawings again which is what I wanted to thanks for helping me with that issue!

**Comment by Seedmanc** [comment]
Try to see what URL Chrome is actually trying to upload the images to. Open Devtools again, go to Network tab and click the '/index.php?page=post&s=add' item once it fails to upload. You'll see some info on the panel, I'm interested in the General section, the Request URL and Remote Address.

Oh and try to choose the smallest image you can for this test, since Chrome might try to show the request contents as text and hang up.

Also I pushed a little fix that removes the Content-Length header from the request. Chrome complained about it in console in the past (you should have probably seen it there). You might need to clear your cache to apply this fix, but I don't know if it'll affect the issue with Chrome not uploading.

**Comment by ssmstzo** [comment]
So I just got a new computer over the weekend and reinstalled FF and Chrome. Turns out they both work fine now? I've been uploading on both all weekend and had no issues. As far as I'm concerned now it's fixed on both platforms (which I think a lot of it was probably on my end). Really appreciate the help you provided me on the issue and the fixes you've implemented because of it. Thanks again!
