### ISSUE TITLE
"Error: Check your posting form URL"

### ISSUE THREAD

**Issue by descourdes** [Seedmanc/Booru-mass-uploader#36]
Just trying to upload some images to blacked.booru.org but I can't seem to do it?

Keeps saying the same thing: [5:20] Couldn't upload filename.png: error, wrong response. Check your posting form URL.
![c2ec302d8e9ba9f05368d431f9279b53](https://user-images.githubusercontent.com/76894817/103472333-4abf3980-4d84-11eb-8a0c-77e9f46a32b8.png)

Would love some clarification as to why, I also cannot for the life of me get it to use HTTP instead of HTTPS I've tried a lot of things so I hope thats not the issue...

**Comment by Seedmanc** [comment]
Registrations are closed, so I can't check it myself, another booru on the same site works fine.
Open devtools in your browser (usually F12 in Chrome), see the network tab and then try to upload something. See what the response of the request says, maybe it'll give more info.

>http

Does booru.org even support that anymore? I think I added a forced redirect to https when Booru added the support. Probably because it didn't work otherwise, but I can't remember now.

**Comment by Ankhanon** [comment]
I wanted to add that the Blacked Booru has recently been given hCaptcha prompts when it comes to logging in and posting anything. I thought this applied to most Boorus from booru.org, but I just noticed that wasn't the case so perhaps that has something to do with this problem?

**Comment by descourdes** [comment]
![6e75f8bffc729f09471cef207724e8b4](https://user-images.githubusercontent.com/76894817/103576997-e7d8ba00-4ecb-11eb-906e-de766c889666.png)

![2cbd127ec02035905bff86a9e2c5c756](https://user-images.githubusercontent.com/76894817/103580084-726fe800-4ed1-11eb-876e-2d0caca71970.png)


Tried looking at the network tab and got this info, can't tell whats up with it though

**Comment by Seedmanc** [comment]
I'm not really familiar with captcha on the Booru.

Regarding the network tab, you'll need the response sub-tab of it, rather than the Headers one.
Do the images appear despite the error, by a chance? Just looking at the 200 OK code it looks as if it worked fine.

Try uploading the images manually via the booru's own page. If it does indeed give captchas on manual upload, there's probably nothing that can be done on the scripts's side, as it uses the same method, just in a loop.

**Comment by descourdes** [comment]
Yeah it needs a captcha to upload an image, guess its RIP?

**Comment by janreggie** [comment]
Same here. While the response yields `200 OK`, the response body contains the appropriate error:

```
<br />Could not add image: Captcha was not solved.
```

**Comment by Seedmanc** [comment]
Nag the booru.org owner, they enabled captcha under the guise of "solving the spam attack", but then the captcha affects even the boorus with closed registrations and no anonymous access, and even when you're the admin. It makes no sense, but the owner don't even allow the creation of new topics on their forums for discussin this problem. 

I guess it's over for them.
